


const data =
{
    "count": 3,
    "results": [
        {
            "listing_id": 863376016,
            "state": "active",
            "user_id": 332759883,
            "category_id": null,
            "title": "Goal Digger",
            "description": "Are you a goal digger and you only waste your time wisely? Then this t-shirt is for you - let the world know!",
            "creation_tsz": 1601146876,
            "ending_tsz": 1611691276,
            "original_creation_tsz": 1601146876,
            "last_modified_tsz": 1601150986,
            "price": "15.00",
            "currency_code": "EUR",
            "quantity": 1,
            "sku": [],
            "tags": [],
            "materials": [],
            "shop_section_id": null,
            "featured_rank": null,
            "state_tsz": 1601146876,
            "url": "https://www.etsy.com/listing/863376016/goal-digger?utm_source=chido&utm_medium=api&utm_campaign=api",
            "views": 2,
            "num_favorers": 0,
            "shipping_template_id": null,
            "processing_min": 1,
            "processing_max": 2,
            "who_made": "i_did",
            "is_supply": "false",
            "when_made": "made_to_order",
            "item_weight": null,
            "item_weight_unit": "g",
            "item_length": null,
            "item_width": null,
            "item_height": null,
            "item_dimensions_unit": "mm",
            "is_private": false,
            "recipient": null,
            "occasion": null,
            "style": null,
            "non_taxable": false,
            "is_customizable": false,
            "is_digital": false,
            "file_data": "",
            "should_auto_renew": false,
            "language": "en-US",
            "has_variations": false,
            "taxonomy_id": 482,
            "taxonomy_path": [
                "Clothing",
                "Unisex Adult Clothing",
                "Tops & Tees",
                "T-shirts"
            ],
            "used_manufacturer": false,
            "is_vintage": false
        },
        {
            "listing_id": 848713746,
            "state": "active",
            "user_id": 332759883,
            "category_id": null,
            "title": "Moscavide the Future",
            "description": "You feel like your neighbourhood is the future? \nYou feel like everyone should share your enthusiasm about your favourite bairro?",
            "creation_tsz": 1598723866,
            "ending_tsz": 1609268266,
            "original_creation_tsz": 1598723866,
            "last_modified_tsz": 1598727936,
            "price": "20.00",
            "currency_code": "EUR",
            "quantity": 1,
            "sku": [],
            "tags": [],
            "materials": [],
            "shop_section_id": null,
            "featured_rank": null,
            "state_tsz": 1598723866,
            "url": "https://www.etsy.com/listing/848713746/moscavide-the-future?utm_source=chido&utm_medium=api&utm_campaign=api",
            "views": 3,
            "num_favorers": 0,
            "shipping_template_id": null,
            "processing_min": 1,
            "processing_max": 2,
            "who_made": "i_did",
            "is_supply": "false",
            "when_made": "made_to_order",
            "item_weight": null,
            "item_weight_unit": "g",
            "item_length": null,
            "item_width": null,
            "item_height": null,
            "item_dimensions_unit": "mm",
            "is_private": false,
            "recipient": null,
            "occasion": null,
            "style": null,
            "non_taxable": false,
            "is_customizable": false,
            "is_digital": false,
            "file_data": "",
            "should_auto_renew": false,
            "language": "en-US",
            "has_variations": true,
            "taxonomy_id": 482,
            "taxonomy_path": [
                "Clothing",
                "Unisex Adult Clothing",
                "Tops & Tees",
                "T-shirts"
            ],
            "used_manufacturer": false,
            "is_vintage": false
        },
        {
            "listing_id": 821807698,
            "state": "active",
            "user_id": 332759883,
            "category_id": null,
            "title": "Presunto Fumado",
            "description": "Wear your statement...or your funny joke on your t-shirt!",
            "creation_tsz": 1594210562,
            "ending_tsz": 1604841362,
            "original_creation_tsz": 1594200698,
            "last_modified_tsz": 1598724799,
            "price": "20.00",
            "currency_code": "EUR",
            "quantity": 1,
            "sku": [],
            "tags": [],
            "materials": [],
            "shop_section_id": null,
            "featured_rank": null,
            "state_tsz": 1594200729,
            "url": "https://www.etsy.com/listing/821807698/presunto-fumado?utm_source=chido&utm_medium=api&utm_campaign=api",
            "views": 13,
            "num_favorers": 0,
            "shipping_template_id": null,
            "processing_min": 1,
            "processing_max": 3,
            "who_made": "i_did",
            "is_supply": "false",
            "when_made": "made_to_order",
            "item_weight": null,
            "item_weight_unit": "g",
            "item_length": null,
            "item_width": null,
            "item_height": null,
            "item_dimensions_unit": "mm",
            "is_private": false,
            "recipient": null,
            "occasion": null,
            "style": null,
            "non_taxable": false,
            "is_customizable": false,
            "is_digital": false,
            "file_data": "",
            "should_auto_renew": false,
            "language": "en-US",
            "has_variations": true,
            "taxonomy_id": 11165,
            "taxonomy_path": [
                "Clothing",
                "Unisex Adult Clothing",
                "Tops & Tees",
                "T-shirts",
                "Graphic Tees"
            ],
            "used_manufacturer": false,
            "is_vintage": false
        }
    ],
    "params": {
        "limit": 25,
        "offset": 0,
        "page": null,
        "shop_id": "24041469",
        "keywords": null,
        "sort_on": "created",
        "sort_order": "down",
        "min_price": null,
        "max_price": null,
        "color": null,
        "color_accuracy": 0,
        "tags": null,
        "taxonomy_id": null,
        "translate_keywords": "false",
        "include_private": 0
    },
    "type": "Listing",
    "pagination": {
        "effective_limit": 25,
        "effective_offset": 0,
        "next_offset": null,
        "effective_page": 1,
        "next_page": null
    }
}

export default data;